services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simao_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - simao_network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: simao_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - simao_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: simao_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: simaorefrigeracao
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: simao
    volumes:
      - simao_mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - simao_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  simao_network:
    driver: bridge

volumes:
  simao_mysql_data:
    driver: local